"""CI-safe guards for the arXiv 2607.19029 §7 amplification (ADR 0088 + ADR 0090).

Unlike the earlier amplifications, this law's theorem and proof are GENERATED by the daemon's own
decision procedure rather than hand-written, so the guards here differ in kind: they pin that the
generator is the source, that the transcribed congruence list really has the properties the law
cites, and that the law does not overclaim the paper's theorem. An opt-in LEIBNIZ_LEAN_E2E=1
anchor does the real discharge + axiom check.
"""
from __future__ import annotations

import importlib.util
import math
import os
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location(
    "cov_law", _ROOT / "scripts" / "export_covering10080_law.py")
cov = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(cov)


def test_transcription_has_every_property_the_law_cites():
    """A mistranscribed residue would make the kernel certify a DIFFERENT object than the one
    cited — the certificate would be honest and the citation false."""
    f = cov.verify_transcription()
    assert f["ok"]
    assert f["n_congruences"] == 66 and f["moduli_distinct"] and f["min_modulus"] == 7
    assert f["lcm"] == 10080 and f["uncovered_residues"] == 0


def test_moduli_are_exactly_the_divisors_of_10080_at_least_7():
    mods = sorted(m for m, _ in cov.SYSTEM)
    assert mods == sorted(d for d in range(7, 10081) if 10080 % d == 0)


def test_theorem_and_proof_come_from_the_generator_not_from_an_edit():
    """The publish path asserts this too. A hand-edited law must not be publishable as
    'kernel-decided' via the daemon's own procedure when the procedure did not produce it."""
    from leibniz.providers.mixed_modulus_prover import mixed_law
    prop = cov.build_propositio()
    regen = mixed_law(cov._NAME, "n >= 0", cov.claim_property())
    assert regen is not None
    assert regen == (prop.expressio.theorem_src, prop.demonstratio.proof_src)


def test_the_claim_is_inside_the_mixed_modulus_fragment():
    """This is what ADR 0088 widened the caps for and ADR 0090 unblocked at the parse boundary:
    before them the claim was refused before any gate saw it."""
    from leibniz.gates.mixed_modulus_decided import classify_mixed
    skel = classify_mixed(cov.claim_property())
    assert skel is not None and skel.M == 10080 and len(skel.atoms) == 66


def test_the_law_does_not_overclaim_the_papers_theorem():
    """The paper's theorem is L_min(7) = 10080 — a MINIMALITY claim resting on complete Gurobi
    computations. Only the construction half is amplified, and the statement must say so, or the
    reading room would assert a Gurobi result as kernel-decided."""
    st = cov.build_propositio().enuntiatio.statement
    assert "construction half" in st.lower()
    assert "not" in st.lower() and "minimal" in st.lower()
    assert "gurobi" in st.lower()


def test_falsifiable_claim_is_actually_falsifiable():
    fc = cov.build_propositio().enuntiatio.falsifiable_claim
    assert "uncovered" in fc.lower() or "none of" in fc.lower()


def test_audited_artifact_records_what_is_and_is_not_established():
    art = (_ROOT / "docs" / "crt" / "covering10080.lean").read_text()
    assert "NOT ESTABLISHED HERE" in art
    assert "arXiv:2607.19029" in art
    assert "REDUNDANT congruence" in art          # the 233 (mod 1120) finding, recorded on purpose
    assert "covering_min_modulus_7_lcm_10080" in art


def test_redundant_congruence_is_recorded_accurately():
    """The artifact claims one congruence is droppable. Verify it, so the note cannot rot."""
    M, drop = 10080, (1120, 233)
    assert drop in cov.SYSTEM
    rest = [(m, c) for m, c in cov.SYSTEM if (m, c) != drop]
    hit = [False] * M
    for m, c in rest:
        for x in range(c % m, M, m):
            hit[x] = True
    assert all(hit), "the note says 233 (mod 1120) is redundant; it is not"
    mods = [m for m, _ in rest]
    lcm = 1
    for m in mods:
        lcm = lcm * m // math.gcd(lcm, m)
    assert len(set(mods)) == 65 and min(mods) == 7 and lcm == 10080


@pytest.mark.skipif(not os.environ.get("LEIBNIZ_LEAN_E2E"), reason="set LEIBNIZ_LEAN_E2E=1 for the Lean e2e")
def test_real_kernel_discharges_with_a_clean_footprint():  # pragma: no cover
    from leibniz.backends.lean_axioms import STD_AXIOMS, axiom_closure
    from leibniz.backends.lean_repl import LeanReplBackend, available
    from leibniz.verifiers import LeanVerifier
    if not available():
        pytest.skip("Lean image unavailable")
    prop = cov.build_propositio()
    ex, de = prop.expressio, prop.demonstratio
    be = LeanReplBackend(timeout_s=900)
    try:
        LeanVerifier(be).discharge(ex, de)
        ax = axiom_closure(be, ex.theorem_src, de.proof_src, ex.imports, preamble=ex.preamble)
    finally:
        be.close()
    assert de.kernel_verified is True and de.qed == "Q.E.D."
    assert ax["ok"] and ax["saw_axiom_report"]
    # ADR 0095: the ALLOWLIST above (`ax["ok"]`) is what actually excludes native computation --
    # since Lean 4.29 the native axiom is auto-generated per computation and named after the
    # theorem (measured on the pinned 4.31: `<name>._native.native_decide.ax_1`), so a denylist
    # naming `Lean.ofReduceBool` never matches and asserts nothing. State the real property.
    assert set(ax["axioms"]) <= STD_AXIOMS, f"footprint outside the allowlist: {ax['axioms']}"
