/-
  Conjecture 4.1 of Bamberg–Giudici–Lansdown–Royle, "Tactical decompositions in finite polar spaces and
  non-spreading classical group actions" (arXiv:2403.17576; Des. Codes Cryptogr. 2024) — kernel-attested base
  case q = 3. The conjecture (still open in general) underpins Theorem 4.2: PΓU(5,q) acting on the totally
  isotropic 1-spaces of H(4,q²) is non-spreading, CONDITIONAL on Conjecture 4.1. Certifying it at q = 3 makes
  that unconditional for q = 3.

  Statement. For b ∈ F_{q²} with b^{q+1} = −1 and (s,u,w) ∈ F_{q²}³ with s^{q+1} = u^{q+1} + w^{q+1}, and for
  κ ∈ F_q^*, let n(κ) = #{ λ ∈ F_{q²} ∪ {∞} : (wλ+1)(b+uλ)^q − (wλ+1)^q(b+uλ) = κ(b²+1+λ²(s²−u²−w²))^{(q+1)/2} }.
  Then n(κ) = n(−κ) for all κ ∈ F_q^*.

  Encoding. F_{q²} = F_q[X]/(X²−r) with r the least non-square mod q (r = 2 for q = 3); an element a0 + a1·X is
  the pair (a0,a1) with coeffs in {0,…,q−1}. Then X^q = −X, so `frob` negates the X-coordinate. λ ∈ F_{q²}∪{∞}
  is handled by homogenising to [λ:μ] on P¹(F_{q²}) (μ = 1 affine, [1:0] at infinity); both sides are degree
  q+1 homogeneous, so the test is projectively well-defined. `validB`, `validSUWnz` (norm cone minus the origin)
  and `p1` are generated by the kernel from (q,r) — no baked data.

    • pgu_q3_symmetry : n(κ) = n(−κ) for every admissible b and every NON-TRIVIAL (s,u,w) on the norm cone.
    • pgu_q3_origin   : the trivial triple (0,0,0) DOES break the symmetry — a discriminating negative control,
                        documenting exactly why the non-degeneracy (s,u,w) ≠ 0 is required.

  Plain `decide` — no `native_decide`, no `sorry`; every theorem depends on no axioms. Report-only.
-/
set_option maxHeartbeats 0
set_option maxRecDepth 1000000

abbrev Fp := Nat × Nat   -- a0 + a1·X in F_q[X]/(X²−r), coeffs in {0,…,q−1}

def fone : Fp := (1, 0)
def fzero : Fp := (0, 0)
def fadd (q : Nat) (x y : Fp) : Fp := ((x.1 + y.1) % q, (x.2 + y.2) % q)
def fsub (q : Nat) (x y : Fp) : Fp := ((x.1 + q - y.1 % q) % q, (x.2 + q - y.2 % q) % q)
def fmul (q r : Nat) (x y : Fp) : Fp :=
  ((x.1 * y.1 + x.2 * y.2 * r) % q, (x.1 * y.2 + x.2 * y.1) % q)
def frob (q : Nat) (x : Fp) : Fp := (x.1 % q, (q - x.2 % q) % q)
def nrm (q r : Nat) (x : Fp) : Nat := (x.1 * x.1 + (q - (x.2 * x.2 * r) % q)) % q
def scal (q k : Nat) : Fp := (k % q, 0)
def fpow (q r : Nat) (x : Fp) (k : Nat) : Fp := (List.range k).foldl (fun acc _ => fmul q r acc x) fone

def allF (q : Nat) : List Fp := (List.range q).flatMap (fun a => (List.range q).map (fun b => (a, b)))
def p1 (q : Nat) : List (Fp × Fp) := (allF q).map (fun x => (x, fone)) ++ [(fone, fzero)]
def fqstar (q : Nat) : List Nat := (List.range q).filter (fun k => k != 0)

def eqAt (q r : Nat) (b s u w : Fp) (k : Nat) (pt : Fp × Fp) : Bool :=
  let lam := pt.1
  let mu := pt.2
  let wlmu := fadd q (fmul q r w lam) mu
  let bmuul := fadd q (fmul q r b mu) (fmul q r u lam)
  let lhs := fsub q (fmul q r wlmu (frob q bmuul)) (fmul q r (frob q wlmu) bmuul)
  let b2p1 := fadd q (fmul q r b b) fone
  let coef := fsub q (fsub q (fmul q r s s) (fmul q r u u)) (fmul q r w w)
  let inside := fadd q (fmul q r b2p1 (fmul q r mu mu)) (fmul q r coef (fmul q r lam lam))
  let base := fpow q r inside ((q + 1) / 2)
  fmul q r (scal q k) base == lhs

def nCount (q r : Nat) (b s u w : Fp) (k : Nat) : Nat := ((p1 q).filter (eqAt q r b s u w k)).length

def validB (q r : Nat) : List Fp := (allF q).filter (fun b => nrm q r b == (q - 1) % q)
def suwAll (q : Nat) : List (Fp × Fp × Fp) :=
  (allF q).flatMap (fun s => (allF q).flatMap (fun u => (allF q).map (fun w => (s, u, w))))
def validSUWnz (q r : Nat) : List (Fp × Fp × Fp) :=
  (suwAll q).filter (fun t =>
    (nrm q r t.1 == (nrm q r t.2.1 + nrm q r t.2.2) % q) &&
    !(t.1 == fzero && t.2.1 == fzero && t.2.2 == fzero))

/-- n(κ) = n(−κ) for every admissible b and every non-trivial (s,u,w) on the norm cone. -/
def symmetryHolds (q r : Nat) : Bool :=
  (validB q r).all (fun b =>
    (validSUWnz q r).all (fun t =>
      (fqstar q).all (fun k =>
        nCount q r b t.1 t.2.1 t.2.2 k == nCount q r b t.1 t.2.1 t.2.2 ((q - k) % q))))

/-- The trivial triple (0,0,0) breaks the symmetry — witnessing that the non-degeneracy is load-bearing. -/
def originBreaks (q r : Nat) : Bool :=
  (validB q r).any (fun b =>
    (fqstar q).any (fun k =>
      nCount q r b fzero fzero fzero k != nCount q r b fzero fzero fzero ((q - k) % q)))

theorem pgu_q3_symmetry : symmetryHolds 3 2 = true := by decide

theorem pgu_q3_origin : originBreaks 3 2 = true := by decide

#print axioms pgu_q3_symmetry
#print axioms pgu_q3_origin
