"""Amplify arXiv 2607.19029 §7 — the distinct covering system with minimum modulus 7 and least
common multiple 10080 — into a promulgated LAW, labelled ``amplified`` + ``kernel-decided``.

This is the target ADR 0088 widened the mixed-modulus fragment for and ADR 0090 unblocked at the
parse boundary. Unlike the earlier amplifications, the theorem and its proof are **generated by
the daemon's own decision procedure**, not hand-written: ``mixed_modulus_prover.mixed_law`` renders
the canonical ℤ-box statement and the ADR 0060 LCM/castHom proof (one ``decide`` over
``ZMod 10080``, one ``intCast`` bridge per atom). The script asserts they came out of the
generator, so a hand-edited law cannot be published through this path.

WHAT IS AMPLIFIED, precisely: the CONSTRUCTION half of the paper's Theorem 1 — that these 66
congruence classes cover the integers, with distinct moduli, least modulus 7, lcm exactly 10080.

WHAT IS NOT: that 10080 is MINIMAL. That is the paper's actual theorem (L_min(7) = 10080), it
rules out every smaller lcm, and it rests on complete Gurobi computations — a commercial ILP
solver standing where a mechanical checker should. Nothing here speaks to it, and re-deciding it
is out of reach. The law's statement says so rather than implying the whole theorem was amplified.

Trust boundary UNTOUCHED: ``kernel_verified`` is written only by ``LeanVerifier.discharge``;
``axiom_closure`` re-checks the whole assembled source; plain ``decide``, no ``native_decide``, no
``sorryAx``. ``tier``/``origination``/``references`` are report-only (ADR 0050).

Usage:  PYTHONPATH=. python scripts/export_covering10080_law.py [--write]
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from leibniz.backends.lean_axioms import axiom_closure  # noqa: E402
from leibniz.backends.lean_repl import LeanReplBackend, available  # noqa: E402
from leibniz.calculemus_site import law_payload  # noqa: E402
from leibniz.propositio import Demonstratio, Enuntiatio, Expressio, Propositio  # noqa: E402
from leibniz.providers.mixed_modulus_prover import mixed_law  # noqa: E402
from leibniz.types import ClaimType  # noqa: E402

_ROOT = Path(__file__).resolve().parent.parent
_ARTIFACT = _ROOT / "docs" / "crt" / "covering10080.lean"
_OUT = _ROOT / "site" / "src" / "content" / "laws" / "covering_min_modulus_7_lcm_10080.json"
_NAME = "covering_min_modulus_7_lcm_10080"

#: arXiv 2607.19029 §7, transcribed from the paper's PDF. Verified exhaustively below before use.
SYSTEM = [
    (7, 6), (8, 7), (9, 8), (10, 6), (12, 9), (14, 8), (15, 12), (16, 3),
    (18, 14), (20, 0), (21, 4), (24, 13), (28, 26), (30, 24), (32, 27), (35, 33),
    (36, 5), (40, 11), (42, 16), (45, 2), (48, 1), (56, 52), (60, 30), (63, 7),
    (70, 28), (72, 29), (80, 59), (84, 10), (90, 74), (96, 43), (105, 93), (112, 73),
    (120, 64), (126, 112), (140, 38), (144, 65), (160, 43), (168, 121), (180, 110), (210, 18),
    (224, 169), (240, 185), (252, 154), (280, 248), (288, 203), (315, 128), (336, 313), (360, 209),
    (420, 292), (480, 75), (504, 217), (560, 404), (630, 578), (672, 505), (720, 281), (840, 472),
    (1008, 553), (1120, 233), (1260, 532), (1440, 875), (1680, 124), (2016, 281), (2520, 2044),
    (3360, 2153), (5040, 5033), (10080, 7193),
]

_REFERENCES = [
    {"citation": ("Zhang, S. & Zhang, J. (2026). A Distinct Covering System with Minimum Modulus 7 "
                  "and Minimal Least Common Multiple 10080. arXiv:2607.19029."),
     "url": "https://arxiv.org/abs/2607.19029"},
]


def verify_transcription() -> dict:
    """Re-derive every property the law names, from the list itself. A mistranscribed residue would
    otherwise make the kernel certify a DIFFERENT object than the one cited."""
    M = 10080
    mods = [m for m, _ in SYSTEM]
    lcm = 1
    for m in mods:
        lcm = lcm * m // math.gcd(lcm, m)
    hit = [False] * M
    for m, c in SYSTEM:
        for x in range(c % m, M, m):
            hit[x] = True
    facts = {
        "n_congruences": len(SYSTEM),
        "moduli_distinct": len(set(mods)) == len(mods),
        "min_modulus": min(mods),
        "lcm": lcm,
        "all_moduli_divide_lcm": all(lcm % m == 0 for m in mods),
        "residues_in_range": all(0 <= c < m for m, c in SYSTEM),
        "uncovered_residues": sum(1 for h in hit if not h),
    }
    facts["ok"] = (facts["moduli_distinct"] and facts["min_modulus"] == 7 and facts["lcm"] == M
                   and facts["all_moduli_divide_lcm"] and facts["residues_in_range"]
                   and facts["uncovered_residues"] == 0)
    return facts


def claim_property() -> str:
    return " or ".join(f"(n % {m} == {c})" for m, c in SYSTEM)


def build_propositio() -> Propositio:
    got = mixed_law(_NAME, "n >= 0", claim_property())
    if got is None:
        raise SystemExit("mixed_law abstained — the claim is outside the mixed-modulus fragment")
    theorem_src, proof_src = got
    en = Enuntiatio(
        statement=("A distinct covering system with minimum modulus 7 and least common multiple "
                   "10080 exists (Zhang & Zhang 2026, §7) — kernel-decided construction half: the "
                   "66 exhibited congruence classes cover every n ≥ 0, their moduli are distinct, "
                   "the least is 7 and their lcm is exactly 10080. The paper's MINIMALITY claim "
                   "(L_min(7) = 10080), which rests on complete Gurobi computations, is NOT "
                   "amplified here and is not implied by this law."),
        claim_type=ClaimType.CORRECTNESS_OVER_DOMAIN,
        falsifiable_claim=("an integer n ≥ 0 lying in none of the 66 classes — equivalently a "
                           "residue mod 10080 left uncovered"),
        claim_domain="n >= 0",
        claim_property=claim_property(),
        domain="number_theory",
    )
    ex = Expressio(theorem_src=theorem_src, imports=("Mathlib",))
    de = Demonstratio(proof_obligation=_NAME, proof_src=proof_src)
    return Propositio(enuntiatio=en, expressio=ex, demonstratio=de)


def main() -> int:
    write = "--write" in sys.argv
    facts = verify_transcription()
    print("=== amplification: arXiv 2607.19029 §7 → covering system law ===")
    print(f"  transcription   : {facts}")
    if not facts["ok"]:
        print("!! the congruence list does not have the cited properties — refusing to proceed.")
        return 1
    if not available():
        print("Lean kernel unavailable (docker/image) — cannot discharge. Aborting.")
        return 2

    prop = build_propositio()
    ex, de = prop.expressio, prop.demonstratio
    # the law must come from the GENERATOR, not from an edit of this file
    regen = mixed_law(_NAME, "n >= 0", claim_property())
    if regen != (ex.theorem_src, de.proof_src):
        print("!! theorem/proof are not what the generator emits — refusing to proceed.")
        return 1

    from leibniz.verifiers import LeanVerifier
    be = LeanReplBackend(timeout_s=900)
    try:
        edge = LeanVerifier(be).discharge(ex, de)          # THE ONLY kernel_verified writer
        ax = axiom_closure(be, ex.theorem_src, de.proof_src, ex.imports, preamble=ex.preamble)
    finally:
        be.close()

    print("  generator       : mixed_modulus_prover.mixed_law (ADR 0060 LCM/castHom)")
    print(f"  kernel_verified : {de.kernel_verified}")
    print(f"  qed             : {de.qed}")
    print(f"  proof edge      : {edge.verdict.value} (producer {edge.producer}, tier {edge.tier.name})")
    print(f"  axiom_closure   : ok={ax['ok']} axioms={ax.get('axioms')} saw_report={ax.get('saw_axiom_report')}")
    if not (de.kernel_verified and de.qed == "Q.E.D." and ax["ok"]):
        print("!! discharge or axiom check failed — NOT emitting a law.")
        return 1

    prop.promulgated = True
    payload = law_payload(prop, published_at="", specimen=False,
                          tier="kernel-decided", origination="amplified", references=_REFERENCES)
    payload["$schema"] = "../../../.astro/collections/laws.schema.json"
    print(f"\n  law id          : {payload['id']}")
    print(f"  tier/origination: {payload['tier']} / {payload['origination']}")
    print(f"  artifact        : {_ARTIFACT.relative_to(_ROOT)}")
    print(f"  theorem_src     : {len(payload['theorem_src'])} chars")
    if write:
        _OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
        print(f"\n  WROTE {_OUT.relative_to(_ROOT)}")
    else:
        print("\n  (dry run — pass --write to emit the law JSON; publication is the operator's "
              "ADR 0033 act)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
