"""Probe β piece 3d — AUTOMORPHISM-PRESCRIBED construction (the witnesses' structural lever).

Unstructured search (exact CP-SAT, heuristic local search) plateaus far below records. The witnesses'
point: records come from STRUCTURE. A code invariant under a permutation group G ≤ S_n is a union of
G-ORBITS of weight-w subsets — so the search collapses from C(n,w) codewords to ~C(n,w)/|G| orbits:

  1. orbits of G on weight-w subsets;
  2. keep "includable" orbits (every internal pair at distance ≥ d);
  3. orbit graph: includable orbits, weight = orbit size, edge = cross-compatible (by G-symmetry,
     check one representative of A against all of B);
  4. MAX-WEIGHT clique on the (small) orbit graph = the best G-invariant code;
  5. union of selected orbits → a valid code (sound witness) → compare to Brouwer → Lean-check a beat.

A G-invariant code is still a fully valid code, so this is a sound LOWER-bound search that happens to
live where records live (cyclic / quasi-cyclic constructions). Groups tried: cyclic Z_n and the
multiplier-extended affine group AGL(1,n) for n prime / small. Untrusted search; verify_cwc + Lean check.

Uses CP-SAT (operator-local) for the small max-weight clique when available, else an exact stdlib
branch-and-bound. Deterministic.
"""
from __future__ import annotations

import json
import sys
import time
from itertools import combinations
from math import gcd
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import cwc_table_oracle as ora  # noqa: E402
from probe_beta_cwc_pilot import verify_cwc  # noqa: E402

try:
    from ortools.sat.python import cp_model
    _HAVE_CP = True
except Exception:
    _HAVE_CP = False


def group_elements(n: int, kind: str) -> list[tuple[int, ...]]:
    """Permutations of {0..n-1} for the prescribed group.
    'cyclic': Z_n shifts i->i+k. 'affine': AGL(1,n) maps i->a*i+b (a coprime to n) — bigger collapse.
    'sub:k': the cyclic SUBGROUP generated by shift^k (order n/gcd(n,k)) — LESS collapse, so it admits
    larger (less-symmetric) codes that full Z_n forbids; sweeping subgroups interpolates symmetry."""
    elems = []
    if kind == "cyclic":
        for k in range(n):
            elems.append(tuple((i + k) % n for i in range(n)))
    elif kind == "affine":
        units = [a for a in range(1, n) if gcd(a, n) == 1]
        for a in units:
            for b in range(n):
                elems.append(tuple((a * i + b) % n for i in range(n)))
    elif kind.startswith("sub:"):
        step = int(kind.split(":")[1]) % n
        order = n // gcd(n, step) if step else 1
        for m in range(order):
            elems.append(tuple((i + m * step) % n for i in range(n)))
    elif kind.startswith("affsub:"):
        # translations x->x+b extended by the MULTIPLIER SUBGROUP <a>: x -> a^j*x + b.
        # Interpolates cyclic (a=1) .. full affine (a primitive). a=n-1 is the dihedral group.
        a = int(kind.split(":")[1]) % n
        powers, p = [], 1 % n
        for _ in range(n):                               # collect <a> (multiplicative order)
            if p in powers:
                break
            powers.append(p)
            p = (p * a) % n
        for j in powers:
            for b in range(n):
                elems.append(tuple((j * i + b) % n for i in range(n)))
    elif kind == "fixcyc":
        # fix coordinate n-1, cyclic Z_{n-1} on {0..n-2} (the "shortened-code" structure)
        for k in range(n - 1):
            elems.append(tuple(((i + k) % (n - 1)) if i < n - 1 else i for i in range(n)))
    else:
        raise ValueError(kind)
    return elems


def candidate_groups(n: int) -> list[str]:
    """A sweep of prescribed groups for a cell: full cyclic, affine, and cyclic subgroups generated by
    shift^k for proper divisors k of n (interpolating from max symmetry to less)."""
    kinds = ["cyclic", "affine"]
    for k in range(2, n):
        if n % k == 0:                                   # subgroup of order n/k
            kinds.append(f"sub:{k}")
    return kinds


def candidate_groups_rich(n: int) -> list[str]:
    """candidate_groups + richer families: affine multiplier-subgroups <a> (incl. dihedral a=n-1) and
    fixed-point cyclic. These reach structures cyclic/affine/cyclic-subgroups cannot express."""
    kinds = candidate_groups(n)
    units = [a for a in range(2, n) if gcd(a, n) == 1]
    for a in units:
        kinds.append(f"affsub:{a}")
    kinds.append("fixcyc")
    return kinds


def orbits(n: int, w: int, elems) -> list[list[frozenset]]:
    """G-orbits of weight-w subsets of {0..n-1}. Each orbit is a list of distinct codewords."""
    seen = set()
    out = []
    for c in combinations(range(n), w):
        s = frozenset(c)
        if s in seen:
            continue
        orb = set()
        for g in elems:
            orb.add(frozenset(g[x] for x in s))
        seen |= orb
        out.append(sorted(orb, key=lambda fs: tuple(sorted(fs))))
    return out


def _dist_ok(a: frozenset, b: frozenset, w: int, d: int) -> bool:
    return 2 * (w - len(a & b)) >= d


def build_orbit_graph(orbs, w: int, d: int):
    """Includable orbits (all internal pairs ≥ d) + their pairwise compatibility (rep of A vs all of
    B). Returns (kept_orbits, weights, adjacency-bitmasks)."""
    kept = []
    for orb in orbs:
        rep = orb[0]
        if all(_dist_ok(rep, o, w, d) for o in orb[1:]):     # internal: rep vs rest (G-transitive)
            kept.append(orb)
    N = len(kept)
    weights = [len(o) for o in kept]
    adj = [0] * N
    for i in range(N):
        ai = kept[i][0]
        for j in range(i + 1, N):
            if all(_dist_ok(ai, o, w, d) for o in kept[j]):   # rep_i vs all of orbit_j
                adj[i] |= (1 << j)
                adj[j] |= (1 << i)
    return kept, weights, adj


def max_weight_clique(weights, adj, deadline: float):
    """Max-weight clique on the (small) orbit graph. CP-SAT if available, else exact B&B."""
    N = len(weights)
    if _HAVE_CP:
        m = cp_model.CpModel()
        x = [m.NewBoolVar(f"x{i}") for i in range(N)]
        for i in range(N):
            for j in range(i + 1, N):
                if not (adj[i] >> j) & 1:
                    m.Add(x[i] + x[j] <= 1)
        m.Maximize(sum(weights[i] * x[i] for i in range(N)))
        s = cp_model.CpSolver()
        s.parameters.max_time_in_seconds = max(1.0, deadline - time.time())
        s.parameters.num_search_workers = 8
        s.Solve(m)
        return [i for i in range(N) if s.Value(x[i]) == 1]
    # stdlib exact B&B (orbit graph is small)
    best = [0, []]

    def expand(cand, chosen, wsum):
        if time.time() > deadline:
            return
        if not cand:
            if wsum > best[0]:
                best[0], best[1] = wsum, list(chosen)
            return
        # bound: remaining weight
        if wsum + sum(weights[i] for i in cand) <= best[0]:
            return
        v = cand[0]
        rest = cand[1:]
        expand([u for u in rest if (adj[v] >> u) & 1], chosen + [v], wsum + weights[v])
        expand(rest, chosen, wsum)

    expand(list(range(N)), [], 0)
    return best[1]


def attempt(n, d, w, snap, kind="cyclic", budget_s=30.0):
    elems = group_elements(n, kind)
    orbs = orbits(n, w, elems)
    kept, weights, adj = build_orbit_graph(orbs, w, d)
    t0 = time.time()
    chosen = max_weight_clique(weights, adj, t0 + budget_s)
    code = [cw for i in chosen for cw in kept[i]]
    ok, _ = verify_cwc(code, n, d, w)
    bk = ora.best_known(n, d, w, snap)
    return {"n": n, "d": d, "w": w, "group": kind, "n_orbits": len(orbs), "includable": len(kept),
            "found": len(code) if ok else 0, "best_known": bk, "verified": ok,
            "beats_record": bool(ok and bk is not None and len(code) > bk),
            "reaches_record": bool(ok and bk is not None and len(code) >= bk),
            "secs": round(time.time() - t0, 1),
            "witness": [sorted(c) for c in code] if (ok and bk is not None and len(code) > bk) else None}


def main() -> int:
    snap, _ = ora.load_snapshot()
    targets = [(14, 6, 6), (15, 6, 5), (14, 6, 5), (13, 6, 5), (17, 6, 4), (18, 6, 4), (19, 6, 4)]
    budget = float(sys.argv[2]) if len(sys.argv) > 2 else 25.0
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("probe_beta_out/automorphism_result.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for n, d, w in targets:
        best_row = None
        for kind in ("cyclic", "affine"):
            r = attempt(n, d, w, snap, kind, budget)
            if best_row is None or r["found"] > best_row["found"]:
                best_row = r
        rows.append(best_row)
        r = best_row
        tag = "*** BEAT ***" if r["beats_record"] else ("reaches record" if r["reaches_record"] else "below record")
        print(f"   A({n},{d},{w}) [{r['group']}] orbits={r['n_orbits']:4d} incl={r['includable']:4d} "
              f"found={r['found']:3d} best_known={r['best_known']} ({r['secs']}s) -> {tag}")
    out.write_text(json.dumps({"cells": len(rows), "beats": sum(r["beats_record"] for r in rows),
                               "reaches": sum(r["reaches_record"] for r in rows), "rows": rows}, indent=2))
    print(f"  BEATS: {sum(r['beats_record'] for r in rows)} | reaches-record: {sum(r['reaches_record'] for r in rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
